### ISSUE TITLE
There are some doubts and issues I am facing if I try to change it according to your instructions for Play store.. Details below ↓

### ISSUE THREAD

**Issue by NomanBaigA** [Udhayarajan/VidSnap#10]
Please clear these doubts -
1) What do I have to change In your Reference 2? It looks like there is nothing I have to do there but at the same time, I thought I have to change something in it.
- I try to remain it same but I am facing a bug during downloading. it stuck at 100%

2) According to your [Reference 3] when I remove half-line. I am facing other issues during the download. 'errors catch by logcat'

There are lots of stuff we have to remove from it for a proper run. Maybe you should put some lines of code for play store purposes and just comment out those codes. so people can directly use it without any issues.

**Comment by Udhayarajan** [comment]
Sure I will  try to add the play store modification in clear steps

**Comment by Udhayarajan** [comment]
Currently, No such plan to add ways that you can publish it over the Play Store. Sorry.
