### ISSUE TITLE
Possible to add Mdisk download support

### ISSUE THREAD

**Issue by natsuneel** [Udhayarajan/VidSnap#13]
Is it possible to add Mdisk video downloading support without 3rd party media players.
Example of above mentioned downloading can be found here in python
https://github.com/death-angel-141/Mdisk-Downloader/blob/main/mdisk.py

**Comment by Udhayarajan** [comment]
okay, I will try my best.

**Comment by Udhayarajan** [comment]
Is it possible for you to provide a few Mdisk URLs?

**Comment by natsuneel** [comment]
https://mdisk.me/convertor/9x4/26ZXaq
https://mdisk.me/convertor/320x143/qgJi27
https://mdisk.me/convertor/45x22/fCKFVF
https://mdisk.me/convertor/2x1/6cPxeg

I hope this helps you.

**Comment by rakitanc** [comment]
> Is it possible for you to provide a few Mdisk URLs?

you can use some help from here

https://github.com/MRKaZ/mDisk-Downloader/releases

**Comment by natsuneel** [comment]
@Udhayarajan we can close this issue. Since main website mdisk is not available no more.

**Comment by Udhayarajan** [comment]
Sure. Thanks
