### ISSUE TITLE
[ INSTAGRAM]: I tried to download lots of reels and IGTV videos with it but it says "Seems to be private video" 

### ISSUE THREAD

**Issue by NomanBaigA** [Udhayarajan/VidSnap#14]

**Comment by Udhayarajan** [comment]
Thanks for the report. Could you please share the App version that you are using?

**Comment by NomanBaigA** [comment]
> Thanks for the report. Could you please share the App version that you are using?

after your reply, I tested again with the latest version( V4.0.0 ). But the same problem

**Comment by Udhayarajan** [comment]
@NomanBaigA  This bug has been fixed with app version 4.0.1. If you still face the issue you can re-open this issue.

**Comment by NomanBaigA** [comment]
> @NomanBaigA This bug has been fixed with app version 4.0.1. If you still face the issue you can re-open this issue.

working perfectly. Thanks :)
