### ISSUE TITLE
[ Feature Request ]: Add Instagram story option because it makes it perfect for Instagram (Details Inside)

### ISSUE THREAD

**Issue by NomanBaigA** [Udhayarajan/VidSnap#15]
I tested it with reels and IGTV video and it worked perfectly. just one thing is MISSING which is the Instagram story option

**Comment by Udhayarajan** [comment]
Currently, status downloader of Instagram is not tested properly and can't assure you it works 💯 fine. Here is a way to download story:

`Copy profile of user who's story needed to be downloaded and past it in url box`

**Comment by NomanBaigA** [comment]
> Currently, story downloader of Instagram is not tested properly and can't assure you it works 💯 fine. Here is a way to download story:
> 
> `Copy profile of user who's story needed to be downloaded and past it in url box`

tested with the videos section and not working. but it should be in the status section with proper working for a better user experience. you can upload it to the play store also after the story part is completed because it's very useful after that

**Comment by Udhayarajan** [comment]
Added in version 5.0.0. It is in beta check it out and give your feedback.

**Comment by NomanBaigA** [comment]
> Added in version 5.0.0. It is in beta check it out and give your feedback.

Sure
