### ISSUE TITLE
I don't like addition files 

### ISSUE THREAD

**Issue by poovarasan96** [Udhayarajan/VidSnap#22]
User when download in play Store directly to download video but why ask this app additional files like fb insta this is irritating to user please consider Direct download via link not additional files please

**Comment by Udhayarajan** [comment]
Sorry, App not available in PlayStore also I would like to inform you that if it is packed with APK it increases the APP size. So it was made to be. Insta won't ask for Additional files anyway Facebook does at some times because of separate audio and video served by Facebook server
