### ISSUE TITLE
Feature request: provide a null-extractor so that it return the original link as the downloadable link.

### ISSUE THREAD

**Issue by NanyangTaiji** [Udhayarajan/VidSnap#24]
In this case, we can you this app as a plain downloader as well that working for those direct links without the need of extraction.

Additionally, when no suitable extractor is found, a dialog can be popup asking whether want to proceed with direct downloading or not.

**Comment by Udhayarajan** [comment]
seems doable but as of now I'm stuck in a tight academic schedule I can't. I gladly accept any PR for this

**Comment by Udhayarajan** [comment]
Done this up to an extent. Don't try with large files keep your file size below 100MB. Also, only video is supported. Don't try with other zip files or so. Then you can't open the History (where you can see the list of downloaded history)

**Comment by NanyangTaiji** [comment]
Thanks
