### ISSUE TITLE
how to remove debug toolbar from all layout files?

### ISSUE THREAD

**Issue by hamza0786** [Udhayarajan/VidSnap#31]
how to remove debug toolbar from all layout files?

**Comment by Udhayarajan** [comment]
I'm not sure what thing you're mentioning. Could you please make it clear

**Comment by hamza0786** [comment]
![Screenshot](https://github.com/Udhayarajan/VidSnap/assets/55581835/19e41c82-3475-48cf-8a83-a16cfe341d3b)
see this how to remove this debug toolbar from all layout files?

**Comment by Udhayarajan** [comment]
`activity_main.xml` needed to be removed. Check `activity_main_preview.xml`

**Comment by hamza0786** [comment]
![Screenshot (3)](https://github.com/Udhayarajan/VidSnap/assets/55581835/8304ef6c-0a34-4fe3-86f5-5dbfa61ce32a)
still same issue i have deleted the file and re-sync cleaned and rebuild the project but not fixed.plz help!

**Comment by Udhayarajan** [comment]
Is this same toolbar appears over apk? If yes kindly send me ss from apk along with apk.

**Comment by hamza0786** [comment]
no only in the design layout and also i have changed the app name but still it showing the Vidsanp[DEBUG].

**Comment by Udhayarajan** [comment]
Since it is not in apk I'm closing this issue, though it is shown in the preview It won't interfere with output just ignore it.
