### ISSUE TITLE
Won't work in android 11. Also the play store will reject the application coz MANAGE_EXTERNAL_STORAGE_PERMISSION

### ISSUE THREAD

**Issue by kushalsharma12** [Udhayarajan/VidSnap#5]

**Comment by Udhayarajan** [comment]
Not only because of `MANAGE_EXTERNAL_STORAGE_PERMISSION`

Refer below wiki page for details:
https://github.com/Udhayarajan/VidSnap/wiki

**Comment by kushalsharma12** [comment]
Bro the situation is if you use MANAGE_EXTERNAL_STORAGE_PERMISSION and your app is uploaded after august than your app will be rejected. And the apps which are using this permission will not be allowed to use this permission after this November, they have to remove it in their next update.

**Comment by Udhayarajan** [comment]
> Bro the situation is if you use MANAGE_EXTERNAL_STORAGE_PERMISSION and your app is uploaded after august than your app will be rejected. And the apps which are using this permission will not be allowed to use this permission after this November, they have to remove it in their next update.

I have fixed this issue bro. Now WhatsApp status saver works without MANAGE_EXTERNAL_STORAGE_PERMISSION
